# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push
env:
  name: mod-report
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
        architecture: x64
    - run: npm install
    - run: npm run build
    - uses: actions/checkout@v2
    - uses: vimtor/action-zip@v1
      with:
        files: dist/
        dest: mod-report.zip
    - name: zip extension
      run: |
        cd dist
        zip ../mod-report.zip *
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          mod-report.zip
